# Generated by Django 6.0.6 on 2026-06-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
